apiVersion: v1
kind: Pod
metadata:
  name: remove-images
  labels:
    name: remove-images
spec:
  nodeName: aks-nodepool1-27292825-vmss000000
  restartPolicy: Never
  containers:
  - name: remove-images
    image: ashnam/remove_images:latest
    volumeMounts:
      - mountPath: /run/containerd/containerd.sock
        name: containerd-sock-volume
    ports:
    - containerPort: 80
    imagePullPolicy: Always
    args:  ["--runtime=containerd", "--imagelist=imagelist-sample"]
  volumes:
  - name: containerd-sock-volume
    hostPath:
      path: /run/containerd/containerd.sock
